language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

env:
  # TERM=dumb : For Gradle build output
  - TERM=dumb
  
script:
  - ./gradlew clean build
